name: 'medical_warehouse'
version: '1.0.0'
config-version: 2

# This must match the name you put in ~/.dbt/profiles.yml
profile: 'medical_warehouse'

# Directory paths for dbt to look for files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring materialization strategies
models:
  medical_warehouse:
    # 1. Staging layer: Clean and standardize raw data. 
    # Best practice: Materialize as views for real-time data flow.
    staging:
      +materialized: view
      +schema: staging

    # 2. Marts layer: Final business-ready tables (Facts & Dimensions).
    # Best practice: Materialize as tables for faster analytical queries.
    marts:
      +materialized: table
      +schema: marts